// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cameras.sql

package store

import (
	"context"
)

const createCamera = `-- name: CreateCamera :one
INSERT INTO cameras (id, name, driver, host, username, password_enc, enabled, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, driver, host, username, password_enc, enabled, status, created_at, updated_at
`

type CreateCameraParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Driver      string `json:"driver"`
	Host        string `json:"host"`
	Username    string `json:"username"`
	PasswordEnc string `json:"password_enc"`
	Enabled     int64  `json:"enabled"`
	Status      string `json:"status"`
}

func (q *Queries) CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, createCamera,
		arg.ID,
		arg.Name,
		arg.Driver,
		arg.Host,
		arg.Username,
		arg.PasswordEnc,
		arg.Enabled,
		arg.Status,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Username,
		&i.PasswordEnc,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCamera = `-- name: DeleteCamera :exec
DELETE FROM cameras WHERE id = ?
`

func (q *Queries) DeleteCamera(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCamera, id)
	return err
}

const getCamera = `-- name: GetCamera :one
SELECT id, name, driver, host, username, password_enc, enabled, status, created_at, updated_at
FROM cameras
WHERE id = ?
`

func (q *Queries) GetCamera(ctx context.Context, id string) (Camera, error) {
	row := q.db.QueryRowContext(ctx, getCamera, id)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Username,
		&i.PasswordEnc,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCameras = `-- name: ListCameras :many
SELECT id, name, driver, host, username, password_enc, enabled, status, created_at, updated_at
FROM cameras
ORDER BY name ASC, created_at ASC
`

func (q *Queries) ListCameras(ctx context.Context) ([]Camera, error) {
	rows, err := q.db.QueryContext(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Driver,
			&i.Host,
			&i.Username,
			&i.PasswordEnc,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamera = `-- name: UpdateCamera :one
UPDATE cameras
SET name = ?,
    driver = ?,
    host = ?,
    username = ?,
    password_enc = ?,
    enabled = ?,
    status = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, driver, host, username, password_enc, enabled, status, created_at, updated_at
`

type UpdateCameraParams struct {
	Name        string `json:"name"`
	Driver      string `json:"driver"`
	Host        string `json:"host"`
	Username    string `json:"username"`
	PasswordEnc string `json:"password_enc"`
	Enabled     int64  `json:"enabled"`
	Status      string `json:"status"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, updateCamera,
		arg.Name,
		arg.Driver,
		arg.Host,
		arg.Username,
		arg.PasswordEnc,
		arg.Enabled,
		arg.Status,
		arg.ID,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Username,
		&i.PasswordEnc,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCameraStatus = `-- name: UpdateCameraStatus :exec
UPDATE cameras
SET status = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateCameraStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateCameraStatus(ctx context.Context, arg UpdateCameraStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCameraStatus, arg.Status, arg.ID)
	return err
}
