// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
	"database/sql"
)

const acknowledgeEvent = `-- name: AcknowledgeEvent :one
UPDATE events
SET acknowledged = 1
WHERE id = ?
RETURNING id, camera_id, type, severity, title, message,
  started_at, ended_at, metadata, thumbnail_path, acknowledged, created_at
`

func (q *Queries) AcknowledgeEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, acknowledgeEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
		&i.ThumbnailPath,
		&i.Acknowledged,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, camera_id, type, severity, title, message,
  started_at, ended_at, metadata, thumbnail_path, acknowledged, created_at
FROM events
WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
		&i.ThumbnailPath,
		&i.Acknowledged,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
  id, camera_id, type, severity, title, message,
  started_at, ended_at, metadata, thumbnail_path, acknowledged
) VALUES (
  ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?
)
RETURNING id, camera_id, type, severity, title, message,
  started_at, ended_at, metadata, thumbnail_path, acknowledged, created_at
`

type InsertEventParams struct {
	ID            string         `json:"id"`
	CameraID      sql.NullString `json:"camera_id"`
	Type          string         `json:"type"`
	Severity      string         `json:"severity"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	StartedAt     string         `json:"started_at"`
	EndedAt       sql.NullString `json:"ended_at"`
	Metadata      string         `json:"metadata"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Acknowledged  int64          `json:"acknowledged"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.ID,
		arg.CameraID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.StartedAt,
		arg.EndedAt,
		arg.Metadata,
		arg.ThumbnailPath,
		arg.Acknowledged,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
		&i.ThumbnailPath,
		&i.Acknowledged,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, camera_id, type, severity, title, message,
  started_at, ended_at, metadata, thumbnail_path, acknowledged, created_at
FROM events
WHERE (cast(?1 AS TEXT) IS NULL OR camera_id = ?1)
  AND (cast(?2 AS TEXT) IS NULL OR type = ?2)
  AND (cast(?3 AS TEXT) IS NULL OR started_at < ?3)
  AND (
    cast(?4 AS INTEGER) IS NULL
    OR ?4 = 0
    OR acknowledged = 0
  )
ORDER BY started_at DESC, id DESC
LIMIT ?5
`

type ListEventsParams struct {
	CameraID    sql.NullString `json:"camera_id"`
	EventType   sql.NullString `json:"event_type"`
	Before      sql.NullString `json:"before"`
	UnackedOnly sql.NullInt64  `json:"unacked_only"`
	LimitCount  int64          `json:"limit_count"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.CameraID,
		arg.EventType,
		arg.Before,
		arg.UnackedOnly,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.StartedAt,
			&i.EndedAt,
			&i.Metadata,
			&i.ThumbnailPath,
			&i.Acknowledged,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
