// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
