// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recordings.sql

package store

import (
	"context"
	"database/sql"
)

const deleteArchivedRecordingsOlderThan = `-- name: DeleteArchivedRecordingsOlderThan :execrows
DELETE FROM recordings
WHERE started_at < ?1
  AND archived_at IS NOT NULL
  AND archived_at != ''
  AND (archive_location IS NULL OR archive_location = '' OR archive_location NOT LIKE 'gdrive:%')
`

func (q *Queries) DeleteArchivedRecordingsOlderThan(ctx context.Context, beforeTs string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteArchivedRecordingsOlderThan, beforeTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recordings WHERE id = ?
`

func (q *Queries) DeleteRecording(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecording, id)
	return err
}

const deleteRecordingsOlderThan = `-- name: DeleteRecordingsOlderThan :execrows
DELETE FROM recordings
WHERE started_at < ?1
  AND (archive_location IS NULL OR archive_location = '' OR archive_location NOT LIKE 'gdrive:%')
`

func (q *Queries) DeleteRecordingsOlderThan(ctx context.Context, beforeTs string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecordingsOlderThan, beforeTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNextRecording = `-- name: GetNextRecording :one
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE camera_id = ?1
  AND started_at > ?2
ORDER BY started_at ASC
LIMIT 1
`

type GetNextRecordingParams struct {
	CameraID string `json:"camera_id"`
	AfterTs  string `json:"after_ts"`
}

func (q *Queries) GetNextRecording(ctx context.Context, arg GetNextRecordingParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getNextRecording, arg.CameraID, arg.AfterTs)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartedAt,
		&i.DurationSec,
		&i.SizeBytes,
		&i.Path,
		&i.Codec,
		&i.ThumbnailPath,
		&i.ArchivedAt,
		&i.ArchiveLocation,
		&i.CreatedAt,
	)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE id = ?
`

func (q *Queries) GetRecording(ctx context.Context, id string) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartedAt,
		&i.DurationSec,
		&i.SizeBytes,
		&i.Path,
		&i.Codec,
		&i.ThumbnailPath,
		&i.ArchivedAt,
		&i.ArchiveLocation,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingAtOrBefore = `-- name: GetRecordingAtOrBefore :one
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE camera_id = ?1
  AND started_at <= ?2
ORDER BY started_at DESC
LIMIT 1
`

type GetRecordingAtOrBeforeParams struct {
	CameraID string `json:"camera_id"`
	AtTs     string `json:"at_ts"`
}

func (q *Queries) GetRecordingAtOrBefore(ctx context.Context, arg GetRecordingAtOrBeforeParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecordingAtOrBefore, arg.CameraID, arg.AtTs)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartedAt,
		&i.DurationSec,
		&i.SizeBytes,
		&i.Path,
		&i.Codec,
		&i.ThumbnailPath,
		&i.ArchivedAt,
		&i.ArchiveLocation,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingByPath = `-- name: GetRecordingByPath :one
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE path = ?
`

func (q *Queries) GetRecordingByPath(ctx context.Context, path string) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecordingByPath, path)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartedAt,
		&i.DurationSec,
		&i.SizeBytes,
		&i.Path,
		&i.Codec,
		&i.ThumbnailPath,
		&i.ArchivedAt,
		&i.ArchiveLocation,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecording = `-- name: InsertRecording :one
INSERT INTO recordings (
  id, camera_id, started_at, duration_sec, size_bytes, path, codec, thumbnail_path
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
  camera_id = excluded.camera_id,
  started_at = excluded.started_at,
  duration_sec = excluded.duration_sec,
  size_bytes = excluded.size_bytes,
  codec = COALESCE(excluded.codec, recordings.codec),
  thumbnail_path = COALESCE(excluded.thumbnail_path, recordings.thumbnail_path)
RETURNING id, camera_id, started_at, duration_sec, size_bytes, path, codec,
          thumbnail_path, archived_at, archive_location, created_at
`

type InsertRecordingParams struct {
	ID            string         `json:"id"`
	CameraID      string         `json:"camera_id"`
	StartedAt     string         `json:"started_at"`
	DurationSec   float64        `json:"duration_sec"`
	SizeBytes     int64          `json:"size_bytes"`
	Path          string         `json:"path"`
	Codec         sql.NullString `json:"codec"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
}

func (q *Queries) InsertRecording(ctx context.Context, arg InsertRecordingParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, insertRecording,
		arg.ID,
		arg.CameraID,
		arg.StartedAt,
		arg.DurationSec,
		arg.SizeBytes,
		arg.Path,
		arg.Codec,
		arg.ThumbnailPath,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartedAt,
		&i.DurationSec,
		&i.SizeBytes,
		&i.Path,
		&i.Codec,
		&i.ThumbnailPath,
		&i.ArchivedAt,
		&i.ArchiveLocation,
		&i.CreatedAt,
	)
	return i, err
}

const listRecordingStorageByCameraRange = `-- name: ListRecordingStorageByCameraRange :many
SELECT started_at, duration_sec, archive_location
FROM recordings
WHERE camera_id = ?1
  AND started_at <= ?2
  AND julianday(started_at) + duration_sec / 86400.0 > julianday(CAST(?3 AS TEXT))
ORDER BY started_at ASC
`

type ListRecordingStorageByCameraRangeParams struct {
	CameraID string `json:"camera_id"`
	ToTs     string `json:"to_ts"`
	FromTs   string `json:"from_ts"`
}

type ListRecordingStorageByCameraRangeRow struct {
	StartedAt       string         `json:"started_at"`
	DurationSec     float64        `json:"duration_sec"`
	ArchiveLocation sql.NullString `json:"archive_location"`
}

func (q *Queries) ListRecordingStorageByCameraRange(ctx context.Context, arg ListRecordingStorageByCameraRangeParams) ([]ListRecordingStorageByCameraRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordingStorageByCameraRange, arg.CameraID, arg.ToTs, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordingStorageByCameraRangeRow{}
	for rows.Next() {
		var i ListRecordingStorageByCameraRangeRow
		if err := rows.Scan(&i.StartedAt, &i.DurationSec, &i.ArchiveLocation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingsByCameraRange = `-- name: ListRecordingsByCameraRange :many
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE camera_id = ?1
  AND started_at <= ?2
  AND julianday(started_at) + duration_sec / 86400.0 > julianday(CAST(?3 AS TEXT))
ORDER BY started_at ASC
`

type ListRecordingsByCameraRangeParams struct {
	CameraID string `json:"camera_id"`
	ToTs     string `json:"to_ts"`
	FromTs   string `json:"from_ts"`
}

func (q *Queries) ListRecordingsByCameraRange(ctx context.Context, arg ListRecordingsByCameraRangeParams) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, listRecordingsByCameraRange, arg.CameraID, arg.ToTs, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.StartedAt,
			&i.DurationSec,
			&i.SizeBytes,
			&i.Path,
			&i.Codec,
			&i.ThumbnailPath,
			&i.ArchivedAt,
			&i.ArchiveLocation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnarchivedRecordings = `-- name: ListUnarchivedRecordings :many
SELECT id, camera_id, started_at, duration_sec, size_bytes, path, codec,
       thumbnail_path, archived_at, archive_location, created_at
FROM recordings
WHERE archived_at IS NULL OR archived_at = ''
ORDER BY started_at ASC
LIMIT ?
`

func (q *Queries) ListUnarchivedRecordings(ctx context.Context, limit int64) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, listUnarchivedRecordings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.StartedAt,
			&i.DurationSec,
			&i.SizeBytes,
			&i.Path,
			&i.Codec,
			&i.ThumbnailPath,
			&i.ArchivedAt,
			&i.ArchiveLocation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecordingArchived = `-- name: MarkRecordingArchived :execrows
UPDATE recordings
SET archived_at = ?, archive_location = ?
WHERE id = ? AND (archived_at IS NULL OR archived_at = '')
`

type MarkRecordingArchivedParams struct {
	ArchivedAt      sql.NullString `json:"archived_at"`
	ArchiveLocation sql.NullString `json:"archive_location"`
	ID              string         `json:"id"`
}

func (q *Queries) MarkRecordingArchived(ctx context.Context, arg MarkRecordingArchivedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRecordingArchived, arg.ArchivedAt, arg.ArchiveLocation, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
