// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
  s.id AS session_id,
  s.user_id,
  s.token_hash,
  s.expires_at,
  s.created_at AS session_created_at,
  u.username,
  u.role
FROM sessions s
INNER JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type GetSessionByTokenHashRow struct {
	SessionID        string `json:"session_id"`
	UserID           string `json:"user_id"`
	TokenHash        string `json:"token_hash"`
	ExpiresAt        string `json:"expires_at"`
	SessionCreatedAt string `json:"session_created_at"`
	Username         string `json:"username"`
	Role             string `json:"role"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.SessionCreatedAt,
		&i.Username,
		&i.Role,
	)
	return i, err
}
