// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stream_profiles.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const deleteStreamProfilesByCamera = `-- name: DeleteStreamProfilesByCamera :exec
DELETE FROM stream_profiles WHERE camera_id = ?
`

func (q *Queries) DeleteStreamProfilesByCamera(ctx context.Context, cameraID string) error {
	_, err := q.db.ExecContext(ctx, deleteStreamProfilesByCamera, cameraID)
	return err
}

const listStreamProfilesByCamera = `-- name: ListStreamProfilesByCamera :many
SELECT id, camera_id, role, rtsp_url, codec, width, height
FROM stream_profiles
WHERE camera_id = ?
ORDER BY role ASC
`

func (q *Queries) ListStreamProfilesByCamera(ctx context.Context, cameraID string) ([]StreamProfile, error) {
	rows, err := q.db.QueryContext(ctx, listStreamProfilesByCamera, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamProfile{}
	for rows.Next() {
		var i StreamProfile
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Role,
			&i.RtspUrl,
			&i.Codec,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamProfilesByCameraIDs = `-- name: ListStreamProfilesByCameraIDs :many
SELECT id, camera_id, role, rtsp_url, codec, width, height
FROM stream_profiles
WHERE camera_id IN (/*SLICE:camera_ids*/?)
ORDER BY camera_id ASC, role ASC
`

func (q *Queries) ListStreamProfilesByCameraIDs(ctx context.Context, cameraIds []string) ([]StreamProfile, error) {
	query := listStreamProfilesByCameraIDs
	var queryParams []interface{}
	if len(cameraIds) > 0 {
		for _, v := range cameraIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:camera_ids*/?", strings.Repeat(",?", len(cameraIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:camera_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamProfile{}
	for rows.Next() {
		var i StreamProfile
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Role,
			&i.RtspUrl,
			&i.Codec,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStreamProfile = `-- name: UpsertStreamProfile :one
INSERT INTO stream_profiles (id, camera_id, role, rtsp_url, codec, width, height)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(camera_id, role) DO UPDATE SET
  rtsp_url = excluded.rtsp_url,
  codec = excluded.codec,
  width = excluded.width,
  height = excluded.height
RETURNING id, camera_id, role, rtsp_url, codec, width, height
`

type UpsertStreamProfileParams struct {
	ID       string         `json:"id"`
	CameraID string         `json:"camera_id"`
	Role     string         `json:"role"`
	RtspUrl  string         `json:"rtsp_url"`
	Codec    sql.NullString `json:"codec"`
	Width    sql.NullInt64  `json:"width"`
	Height   sql.NullInt64  `json:"height"`
}

func (q *Queries) UpsertStreamProfile(ctx context.Context, arg UpsertStreamProfileParams) (StreamProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertStreamProfile,
		arg.ID,
		arg.CameraID,
		arg.Role,
		arg.RtspUrl,
		arg.Codec,
		arg.Width,
		arg.Height,
	)
	var i StreamProfile
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Role,
		&i.RtspUrl,
		&i.Codec,
		&i.Width,
		&i.Height,
	)
	return i, err
}
