// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CameraStatus.
const (
	Offline CameraStatus = "offline"
	Online  CameraStatus = "online"
	Unknown CameraStatus = "unknown"
)

// Valid indicates whether the value is a known member of the CameraStatus enum.
func (e CameraStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for CreateUserRequestRole.
const (
	CreateUserRequestRoleAdmin    CreateUserRequestRole = "admin"
	CreateUserRequestRoleOperator CreateUserRequestRole = "operator"
	CreateUserRequestRoleViewer   CreateUserRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the CreateUserRequestRole enum.
func (e CreateUserRequestRole) Valid() bool {
	switch e {
	case CreateUserRequestRoleAdmin:
		return true
	case CreateUserRequestRoleOperator:
		return true
	case CreateUserRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for EventSeverity.
const (
	Critical EventSeverity = "critical"
	Info     EventSeverity = "info"
	Warning  EventSeverity = "warning"
)

// Valid indicates whether the value is a known member of the EventSeverity enum.
func (e EventSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for StreamProfileRole.
const (
	Live   StreamProfileRole = "live"
	Record StreamProfileRole = "record"
)

// Valid indicates whether the value is a known member of the StreamProfileRole enum.
func (e StreamProfileRole) Valid() bool {
	switch e {
	case Live:
		return true
	case Record:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusHealthStatus.
const (
	SystemStatusHealthStatusDegraded SystemStatusHealthStatus = "degraded"
	SystemStatusHealthStatusOk       SystemStatusHealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the SystemStatusHealthStatus enum.
func (e SystemStatusHealthStatus) Valid() bool {
	switch e {
	case SystemStatusHealthStatusDegraded:
		return true
	case SystemStatusHealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for UserPublicRole.
const (
	UserPublicRoleAdmin    UserPublicRole = "admin"
	UserPublicRoleOperator UserPublicRole = "operator"
	UserPublicRoleViewer   UserPublicRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserPublicRole enum.
func (e UserPublicRole) Valid() bool {
	switch e {
	case UserPublicRoleAdmin:
		return true
	case UserPublicRoleOperator:
		return true
	case UserPublicRoleViewer:
		return true
	default:
		return false
	}
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	SetupRequired bool        `json:"setupRequired"`
	User          *UserPublic `json:"user,omitempty"`
}

// Camera defines model for Camera.
type Camera struct {
	CreatedAt time.Time `json:"createdAt"`

	// Driver Camera driver identifier (e.g. generic-rtsp)
	Driver  string `json:"driver"`
	Enabled bool   `json:"enabled"`

	// Host Display host or primary RTSP base
	Host           string             `json:"host"`
	Id             openapi_types.UUID `json:"id"`
	Name           string             `json:"name"`
	Status         CameraStatus       `json:"status"`
	StreamProfiles []StreamProfile    `json:"streamProfiles"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// CameraStatus defines model for Camera.Status.
type CameraStatus string

// CoverageBar Timeline UI aggregation bar (can match segments for phase 4)
type CoverageBar struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

// CreateCameraRequest defines model for CreateCameraRequest.
type CreateCameraRequest struct {
	Driver  *string `json:"driver,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`
	Host    string  `json:"host"`

	// LiveRtspUrl Live stream RTSP URL; if omitted, may be derived later
	LiveRtspUrl *string `json:"liveRtspUrl,omitempty"`
	Name        string  `json:"name"`
	Password    *string `json:"password,omitempty"`

	// RecordRtspUrl Record stream RTSP URL
	RecordRtspUrl *string `json:"recordRtspUrl,omitempty"`
	Username      *string `json:"username,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Password string                `json:"password"`
	Role     CreateUserRequestRole `json:"role"`
	Username string                `json:"username"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// DiskInfo defines model for DiskInfo.
type DiskInfo struct {
	FreeBytes   int64   `json:"freeBytes"`
	Path        string  `json:"path"`
	TotalBytes  int64   `json:"totalBytes"`
	UsedBytes   int64   `json:"usedBytes"`
	UsedPercent float32 `json:"usedPercent"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Acknowledged bool                    `json:"acknowledged"`
	CameraId     *string                 `json:"cameraId,omitempty"`
	CreatedAt    time.Time               `json:"createdAt"`
	EndedAt      *time.Time              `json:"endedAt,omitempty"`
	Id           string                  `json:"id"`
	Message      string                  `json:"message"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Severity     EventSeverity           `json:"severity"`
	StartedAt    time.Time               `json:"startedAt"`
	Title        string                  `json:"title"`
	Type         string                  `json:"type"`
}

// EventSeverity defines model for Event.Severity.
type EventSeverity string

// EventList defines model for EventList.
type EventList struct {
	Events []Event `json:"events"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LiveStream defines model for LiveStream.
type LiveStream struct {
	// CameraId Camera ID for this live session
	CameraId string `json:"cameraId"`

	// ExpiresAt When the stream token expires
	ExpiresAt time.Time `json:"expiresAt"`

	// HlsUrl Full or relative URL for HLS playback
	HlsUrl string `json:"hlsUrl"`

	// Token Stream token to pass as query `?token=` or header as documented
	Token string `json:"token"`

	// WhepUrl Full or relative URL for WHEP playback
	WhepUrl string `json:"whepUrl"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PatchSettingsRequest defines model for PatchSettingsRequest.
type PatchSettingsRequest struct {
	RecordingEnabled *bool `json:"recordingEnabled,omitempty"`

	// RecordingsDir Absolute or relative path on the NVR server for new recordings.
	RecordingsDir *string `json:"recordingsDir,omitempty"`
	RetentionDays *int    `json:"retentionDays,omitempty"`
	SiteName      *string `json:"siteName,omitempty"`
}

// PlaybackRequest defines model for PlaybackRequest.
type PlaybackRequest struct {
	// DurationSec Playback window length in seconds
	DurationSec *float32  `json:"durationSec,omitempty"`
	Start       time.Time `json:"start"`
}

// PlaybackSession defines model for PlaybackSession.
type PlaybackSession struct {
	CameraId    string    `json:"cameraId"`
	ExpiresAt   time.Time `json:"expiresAt"`
	PlaybackUrl string    `json:"playbackUrl"`
	Token       string    `json:"token"`
}

// ProbeCameraRequest defines model for ProbeCameraRequest.
type ProbeCameraRequest struct {
	Password *string `json:"password,omitempty"`
	RtspUrl  string  `json:"rtspUrl"`
	Username *string `json:"username,omitempty"`
}

// ProbeResult defines model for ProbeResult.
type ProbeResult struct {
	Codec *string `json:"codec,omitempty"`
	Error *string `json:"error,omitempty"`

	// H265 True if codec looks like hevc/h265
	H265      bool `json:"h265"`
	Height    *int `json:"height,omitempty"`
	Reachable bool `json:"reachable"`
	Width     *int `json:"width,omitempty"`
}

// RecordingList defines model for RecordingList.
type RecordingList struct {
	Coverage   []CoverageBar      `json:"coverage"`
	Recordings []RecordingSegment `json:"recordings"`
}

// RecordingSegment defines model for RecordingSegment.
type RecordingSegment struct {
	CameraId    string  `json:"cameraId"`
	Codec       *string `json:"codec,omitempty"`
	DurationSec float32 `json:"durationSec"`
	Id          string  `json:"id"`

	// Path Relative storage path
	Path         string    `json:"path"`
	SizeBytes    int64     `json:"sizeBytes"`
	StartedAt    time.Time `json:"startedAt"`
	ThumbnailUrl *string   `json:"thumbnailUrl,omitempty"`
}

// Settings defines model for Settings.
type Settings struct {
	// RecordingEnabled When false, MediaMTX continuous recording is disabled for all cameras.
	RecordingEnabled bool `json:"recordingEnabled"`

	// RecordingsDir Absolute or relative path on the NVR server where recordings are stored.
	RecordingsDir string `json:"recordingsDir"`
	RetentionDays int    `json:"retentionDays"`
	SiteName      string `json:"siteName"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// StreamProfile defines model for StreamProfile.
type StreamProfile struct {
	Codec   *string           `json:"codec,omitempty"`
	Height  *int              `json:"height,omitempty"`
	Id      string            `json:"id"`
	Role    StreamProfileRole `json:"role"`
	RtspUrl string            `json:"rtspUrl"`
	Width   *int              `json:"width,omitempty"`
}

// StreamProfileRole defines model for StreamProfile.Role.
type StreamProfileRole string

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	Cameras struct {
		Enabled int `json:"enabled"`
		Online  int `json:"online"`
		Total   int `json:"total"`
	} `json:"cameras"`
	Commit string   `json:"commit"`
	Disk   DiskInfo `json:"disk"`
	Health struct {
		Status SystemStatusHealthStatus `json:"status"`
	} `json:"health"`
	RetentionDays int    `json:"retentionDays"`
	Version       string `json:"version"`
}

// SystemStatusHealthStatus defines model for SystemStatus.Health.Status.
type SystemStatusHealthStatus string

// UpdateCameraRequest defines model for UpdateCameraRequest.
type UpdateCameraRequest struct {
	Driver        *string `json:"driver,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
	Host          *string `json:"host,omitempty"`
	LiveRtspUrl   *string `json:"liveRtspUrl,omitempty"`
	Name          *string `json:"name,omitempty"`
	Password      *string `json:"password,omitempty"`
	RecordRtspUrl *string `json:"recordRtspUrl,omitempty"`
	Username      *string `json:"username,omitempty"`
}

// UserPublic defines model for UserPublic.
type UserPublic struct {
	Id       string         `json:"id"`
	Role     UserPublicRole `json:"role"`
	Username string         `json:"username"`
}

// UserPublicRole defines model for UserPublic.Role.
type UserPublicRole string

// Version defines model for Version.
type Version struct {
	Commit  string `json:"commit"`
	Version string `json:"version"`
}

// ListCameraRecordingsParams defines parameters for ListCameraRecordings.
type ListCameraRecordingsParams struct {
	// From Range start (inclusive)
	From time.Time `form:"from" json:"from"`

	// To Range end (inclusive)
	To time.Time `form:"to" json:"to"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Cursor — return events before this timestamp
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// CameraId Filter by camera ID
	CameraId *openapi_types.UUID `form:"cameraId,omitempty" json:"cameraId,omitempty"`

	// Type Filter by event type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// UnacknowledgedOnly When true, only return unacknowledged events
	UnacknowledgedOnly *bool `form:"unacknowledgedOnly,omitempty" json:"unacknowledgedOnly,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthSetupJSONRequestBody defines body for PostAuthSetup for application/json ContentType.
type PostAuthSetupJSONRequestBody = SetupRequest

// CreateCameraJSONRequestBody defines body for CreateCamera for application/json ContentType.
type CreateCameraJSONRequestBody = CreateCameraRequest

// ProbeCameraJSONRequestBody defines body for ProbeCamera for application/json ContentType.
type ProbeCameraJSONRequestBody = ProbeCameraRequest

// UpdateCameraJSONRequestBody defines body for UpdateCamera for application/json ContentType.
type UpdateCameraJSONRequestBody = UpdateCameraRequest

// PostCameraPlaybackJSONRequestBody defines body for PostCameraPlayback for application/json ContentType.
type PostCameraPlaybackJSONRequestBody = PlaybackRequest

// PatchSettingsJSONRequestBody defines body for PatchSettings for application/json ContentType.
type PatchSettingsJSONRequestBody = PatchSettingsRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostAuthLogin Log in
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// PostAuthLogout Log out
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// GetAuthMe Current user
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// PostAuthSetup Initial admin setup
	// (POST /auth/setup)
	PostAuthSetup(w http.ResponseWriter, r *http.Request)
	// GetAuthStatus Authentication status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// ListCameras List cameras
	// (GET /cameras)
	ListCameras(w http.ResponseWriter, r *http.Request)
	// CreateCamera Create camera
	// (POST /cameras)
	CreateCamera(w http.ResponseWriter, r *http.Request)
	// ProbeCamera Probe RTSP stream
	// (POST /cameras/probe)
	ProbeCamera(w http.ResponseWriter, r *http.Request)
	// DeleteCamera Delete camera
	// (DELETE /cameras/{id})
	DeleteCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetCamera Get camera
	// (GET /cameras/{id})
	GetCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateCamera Update camera
	// (PATCH /cameras/{id})
	UpdateCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostCameraLive Start or get live stream endpoints
	// (POST /cameras/{id}/live)
	PostCameraLive(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostCameraPlayback Start playback session
	// (POST /cameras/{id}/playback)
	PostCameraPlayback(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListCameraRecordings List camera recordings
	// (GET /cameras/{id}/recordings)
	ListCameraRecordings(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCameraRecordingsParams)
	// GetCameraSnapshot Camera snapshot
	// (GET /cameras/{id}/snapshot)
	GetCameraSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListEvents List events
	// (GET /events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// AcknowledgeEvent Acknowledge an event
	// (POST /events/{id}/acknowledge)
	AcknowledgeEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetSettings Get settings
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// PatchSettings Update settings
	// (PATCH /settings)
	PatchSettings(w http.ResponseWriter, r *http.Request)
	// GetSystemDisk Disk usage
	// (GET /system/disk)
	GetSystemDisk(w http.ResponseWriter, r *http.Request)
	// GetSystemStatus System status overview
	// (GET /system/status)
	GetSystemStatus(w http.ResponseWriter, r *http.Request)

	// (GET /system/version)
	GetVersion(w http.ResponseWriter, r *http.Request)
	// ListUsers List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// CreateUser Create user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Delete user
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PostAuthLogin Log in
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostAuthLogout Log out
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthMe Current user
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostAuthSetup Initial admin setup
// (POST /auth/setup)
func (_ Unimplemented) PostAuthSetup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthStatus Authentication status
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCameras List cameras
// (GET /cameras)
func (_ Unimplemented) ListCameras(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCamera Create camera
// (POST /cameras)
func (_ Unimplemented) CreateCamera(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ProbeCamera Probe RTSP stream
// (POST /cameras/probe)
func (_ Unimplemented) ProbeCamera(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCamera Delete camera
// (DELETE /cameras/{id})
func (_ Unimplemented) DeleteCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCamera Get camera
// (GET /cameras/{id})
func (_ Unimplemented) GetCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCamera Update camera
// (PATCH /cameras/{id})
func (_ Unimplemented) UpdateCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostCameraLive Start or get live stream endpoints
// (POST /cameras/{id}/live)
func (_ Unimplemented) PostCameraLive(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostCameraPlayback Start playback session
// (POST /cameras/{id}/playback)
func (_ Unimplemented) PostCameraPlayback(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCameraRecordings List camera recordings
// (GET /cameras/{id}/recordings)
func (_ Unimplemented) ListCameraRecordings(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCameraRecordingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCameraSnapshot Camera snapshot
// (GET /cameras/{id}/snapshot)
func (_ Unimplemented) GetCameraSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEvents List events
// (GET /events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AcknowledgeEvent Acknowledge an event
// (POST /events/{id}/acknowledge)
func (_ Unimplemented) AcknowledgeEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSettings Get settings
// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PatchSettings Update settings
// (PATCH /settings)
func (_ Unimplemented) PatchSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSystemDisk Disk usage
// (GET /system/disk)
func (_ Unimplemented) GetSystemDisk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSystemStatus System status overview
// (GET /system/status)
func (_ Unimplemented) GetSystemStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /system/version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUsers List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateUser Create user
// (POST /users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteUser Delete user
// (DELETE /users/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSetup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCameras operation middleware
func (siw *ServerInterfaceWrapper) ListCameras(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCameras(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCamera operation middleware
func (siw *ServerInterfaceWrapper) CreateCamera(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCamera(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProbeCamera operation middleware
func (siw *ServerInterfaceWrapper) ProbeCamera(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProbeCamera(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCamera operation middleware
func (siw *ServerInterfaceWrapper) DeleteCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCamera operation middleware
func (siw *ServerInterfaceWrapper) GetCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCamera operation middleware
func (siw *ServerInterfaceWrapper) UpdateCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCameraLive operation middleware
func (siw *ServerInterfaceWrapper) PostCameraLive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCameraLive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCameraPlayback operation middleware
func (siw *ServerInterfaceWrapper) PostCameraPlayback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCameraPlayback(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCameraRecordings operation middleware
func (siw *ServerInterfaceWrapper) ListCameraRecordings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCameraRecordingsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCameraRecordings(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCameraSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetCameraSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCameraSnapshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cameraId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cameraId", r.URL.Query(), &params.CameraId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cameraId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cameraId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unacknowledgedOnly" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unacknowledgedOnly", r.URL.Query(), &params.UnacknowledgedOnly, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unacknowledgedOnly"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unacknowledgedOnly", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcknowledgeEvent operation middleware
func (siw *ServerInterfaceWrapper) AcknowledgeEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcknowledgeEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemDisk operation middleware
func (siw *ServerInterfaceWrapper) GetSystemDisk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemDisk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/version", wrapper.GetVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/setup", wrapper.PostAuthSetup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras", wrapper.ListCameras)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras", wrapper.CreateCamera)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/probe", wrapper.ProbeCamera)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cameras/{id}", wrapper.DeleteCamera)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}", wrapper.GetCamera)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/cameras/{id}", wrapper.UpdateCamera)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/{id}/live", wrapper.PostCameraLive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}/snapshot", wrapper.GetCameraSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}/recordings", wrapper.ListCameraRecordings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/{id}/playback", wrapper.PostCameraPlayback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{id}/acknowledge", wrapper.AcknowledgeEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/disk", wrapper.GetSystemDisk)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/status", wrapper.GetSystemStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/settings", wrapper.PatchSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzvjts2tn8VQvd+SABnPGnT4naKi0WapEm2k9YYN+0C6WBDS8cyOxKpkpRdbzDAPsQ+4T7Jgv8kSqJk",
	"eRJ7Mpt8S0YSef6f3zk89LsoZnnBKFAporN3kYhXkGP9z8elXM0llqX+X8FZAVwSMK+BLIsL+KMkHBL1",
	"B7ktIDqLFoxlgGl0PYlKAVw9+V8Oy+gs+p9pvdHU7jJ9LYDPykVG4uj6ehLxasE3rR0uJ24HtvgdYqk2",
	"eIJz4LhLW8wBS0geS/WfJeM5ltFZlGAJDyTJIaqWEpITmqqlEk7WhtoERMxJIQmj0ZndApnHiCRAJVkS",
	"4OgenKQnKAUKnMQPuBTF/dC6QPEi6xPQignZ3fIpEUWGt0g9RYyjgpMc8y26+Hk+QwssgvSTpMFrWZIk",
	"9BrFOXi01A9EpeYElrjM9CL0irINjRQXZa5UwmhGqNqfLZf2X+6ly0loUQ44n3G2JJnRDJGQi102Mfc/",
	"U+vYhTHneKsNq0j202/LsrRstCgqxdeasmqpRNJhY+LZl09L0ELZGjhO4TscsK2fSQ5Kiuj1S4TTlEOK",
	"1RO0wBzdizFFOZbxCglIcyUftFTGsMIC0CNla02bB5qMt3YhMb+p8My3E71hkGUtHOM3ynvB2HiTWt/d",
	"nLn5vrTDlaqPJC9hMuBZnUUysoYLKYrXPOsq5JysARltG297fXH+LSJLxHIiJSQTlOMtWgBKQNGfoAxL",
	"bTu9fpYTeg40lavo7GHgtQILsWE8CZLKIWY86SX2Qj9ukxsiRsXhHsdv6db6hJZev25VzO7VrM+Sx/3/",
	"BejiLANjuia64CQnKtqo5bBkSrBrAhvgweDiczUo5haP1Xee+C0tIZafEnH1ki5Zl9MlB/huK+1/nCMR",
	"Kr9+VGuBUAkpcKNsRV9A0ZJJnO2zUikg2ff9GfAYqO8UtMwX6nlLPprMBlH+hhOP7ebCIeE945zxQH5m",
	"STgLgXt/WIXmteCGa8tjc0McqySVQZL2peJYx6uX+ikts0yFmlZ4qcm8Ab4Amgx+sHNPEg4SOQiBU+h5",
	"JnGCpQZIOEmIChw4m3mSaexVS1HAGjiRW985ifKBSbTBnKrllRCIJDHOejI/5ntKSBKZhfkwf3g3Jqnr",
	"VzwG3LK1oHzaJk3D8BXba1znJBT1YO3g8yiEY8y0g2zaZm4WDZHyAnBmokkLlVcwroJsVwrkQMpx0kDR",
	"/dldLRDaU2VHA80CHu25TxBAv3yq4YtcEYEynWZBCPVGyFf+LAgH8TiAjX9dAUVyVWVpya6AIvuBCk6j",
	"TG2ViWBK/b7MMoW4OWRYKiJfX5xrsl+cz5HC5AscXwVtV5HRXW/uEykZUvkGYYH+KIFv0du/6Af//1Zt",
	"uQKcAFcPExaXCu9BEMBvVlDsR/uvL57NBohv6b9SZL1VJS/Hp6+hoKGwlNB9AcLDA6f4EKEzha/nICWh",
	"qegl2OAwQtNnQ7Vc9ZZ4SgJY//FCsKyU0FCRSrWIGYP+8ZcLJICrKlNpjcIG1UuehEyBg1TVKKNP8VZY",
	"EZFcef3DEAgQRMKPvSiwKxtrMf0QvuS6XJlD3IDkX59OWry7pdCG0IRtUKb1iAhFAmJGE1Fz5zDJhyhR",
	"Lge4mtvoMxjIhgPTuFDjHM/6bH/kGO2W/opjPXLG2WJXSTZci9RVyB4+O8yTW7OX4AsQ2qJC8DHeCz9O",
	"otUXX38VqMB5Caq+0yuijLErlZ2uAK1gHU/1N8HqEki68qG052YccLwySC4UJjYkaVQB1Zdt4VTLWNpD",
	"UrpwASIMSmLbfBgNS/xuRaDtUsej0StWFM5NE2Mn5vH2mNQMDDLvlt7Pl/uNqBXYOpGpB4m78q5dpdtY",
	"LyRTrCBXXnUQM/nHXtXkTRD2qswXFJPMevKOmiOEr7045MNoX2Q+K1YqIfW5tDsu3wZQ4BJnAiboFSQE",
	"v/r5byhmVBJaslLUiRMRgRIi9DI6reIsQ4YHP6ceJo1vVsDBS+IIc2MGkIzL5/vm8KYf+Yt5X7ZZnHTl",
	"3aMu04x/36bPoTFds3ncnzt2FtxDQb4nBLQbWqrQqQQcrJO9vNqF+iNTBan6V5PBnDrfCgl533mO9YpA",
	"adtBvZ4g7IFA8JnuII2g37znN+DtqiEmYpbnJNzaTYi42pWPqm6eVvDxa+gRPr4G7qDp8DbuxUooFUtW",
	"FpNKqe2NQ6S91gcZo/v2Nzvp2tWPP04jfU/Q2hVVfWjZkdDI0HDzXveILO3Fyt6+9i+1mbUjZK+H3dw0",
	"uxToNmNcciK3c+WcbnN2ReBxGYJStmZD5h1EhCghUXk3YymhKiPrE2OVW4l637znTvrOIrrmf+90nXBB",
	"fgAFQ1VUt23+VgOLUclxLDV+eM7QPYYL8kDlkRTofYRpggocX+EUxFQ/yQhQie6xAqj6v9rIrHf/pOpH",
	"nkUKKDyevYw8qUanJw9PTnVYNd9GZ9GX+k8GR2kJTXEpV1PNstZd8AhZCVC5e4wlCLQhcoWcTViCjbuc",
	"/EZ/okiUcQxCTBB2XTkn47eezN4qMCVAojXBaA7ywRP9zslvtRkTRhXajmZMSEWCbgRFxjRAyO9YsjVK",
	"ptICdlwUmaKSMDr9XRjTMrF6VyRvNJmumwaoMrr+gygYFcayvjg9/WB7N4YWricDwk++bYtUgA3UCXBN",
	"WC3KnSbfUIcCdRW1bXdUVD36gBybg5wAsy/pGmckQVbFaKF0rDd/eLzNYw56MANnwgSWMs8x30Zn0TlL",
	"kTZBiVWp8SZS3hNdqpcqR2Kl7PekZzQRGtjHJefKr506lRvFGWBuHjc9xejrZMgx1K4dE30UOJNmaarC",
	"XCkDrJlF+ngz+SIFGSpLZcmpIR379qrjhG3Vd5juMvQcND+vILo1d/vph6PZ22vakFUjiUVnb5rp683l",
	"9aWvrydWlnoqql9pOof126M5gTeKWxIuJNJIwqhto+piyvR/BII/iZAHjvC6LDxQhG+UnKMi/MMjmZx6",
	"iuxZ4acb4L85gsNpQ8YZB5xsjUF/a1AeokwinGVs4/ywcrSXlKhUYB1DWAvt9beq2hsMlJsVyBVwROzi",
	"hggikLNJnRBCiUJ7Jlk2w2xvJJ27obODRVNvl55o2pCmh2YUN9VQXECeXgvByrLJ4jkR8olXkb4Hg729",
	"i3F9bjM3uqsX7ZYNFC93NgspHaC6LeC0WLGqammbeJrK88f6DhTwQ5ODR477zjK6UrdzDDbqR58Evn4/",
	"vKMlZW0taGpezJgWnC2gH/bo80CBMK0GHTVGtadkJCNyqwOwHQtxk0+69GWlNGojNEXYEhTA5vUZ6YHs",
	"O3AKe+TC1T9WDehbP0bcPv9s4Tss3IhLG6Sxu51W/o4k18a4M5DQDbJP9d89I9xVHbrrCfq75PbEpvZ9",
	"dPh9LbsK+y1ZSffUl5HuUESahIHLc5B9Ojk9Quq5TWxxJxT7HOSwVgvMcQ5SF2RveicUXePYHtHbtrE5",
	"XmuEaL8w23HlRhFaYBmvulblH7gcKOOEznSOnHJ2Iip7geYTzTd3wr+MGY2FcirJTfXRt54MuFXPC4JJ",
	"V9P/+uLZbOqP9ipcKTSOxEisGJcPMn3NpzFsXPVGDY78jc6wMP048zww33uPtSZ70WKrv8ghIRhleAv8",
	"fl+bzQjp3I0SHMhNveHugPn4F6OAJgUjVIrbdZovD7/v94wvSJIAvUU3PVKjzeFIOyu1X3iYS8z1TdUU",
	"pB3ub5vKqJhRDal/pHHD9d6bwaEKHq7hZwrTmPEEErQmCTCkZ+V0+Sm136dkDRRJksOw18/qsf2DFKSt",
	"Ge9jV6OtYexQRdoS7ieYqI8UASpJ68b6GhMzHXeDQNB2iHHO3xwuHuzF1+Od1dVofRprp4XRAnNzWdo1",
	"e3QbiNCW6yGOaRp0wLpRfeGPIw/GpAu1mHF0dI/QOCsFWcN9F6E0JKhD1JKzfFyQGrz1ECYCaDKCBMne",
	"n4DLA0aH5nB7wGKrF1BGhDRTLtXE+GdAP/IUADUm7j+24rkTJgTFhVgxuTNIYPTX2bPnyL2P2NJD7fo8",
	"zsW44Fmc4Wvudttp5yTHKUx/LyBtKrficEEo1u7XOcltq7ZB96diyIzXqnqPDGRXE7XePkaLrm8L956T",
	"PjOv7KD1Ff6T5GWOzOUUZeNmaSQZ4toReoJ/RszAcE14dX/vq9NJlJt1o7MvTk8ngfntjsxKLhhH//7n",
	"v+y2jo4FLBkHc+1X5RAhcV700GTejd4/C35PMglc1dhxW5etLf3rLKNVOLCf5hrZS+jBpGvvp/fOdUzC",
	"N56VlSFGs62Tb0n9q+tW3D2bNt/9iWbbEAnVtPZBs3p9hz4QC/RDnc3v0GF6JXoXady1/eva1U3u8rSw",
	"s8Q1ojh8hduMPI9rCs1PFBzaEvqtoPHLDP/tSdCwfEMw5ykNYRt5+8yxvvPSd9D1wl0hOZji7Q79w0eO",
	"cqEvLFnKhXdfsI/26k7hAamv9rjDQ0DPQSJRy6qSt/uTwUj20Ko13K6H6lQmOkEOaj86/VIBagOvsww4",
	"IsKAOGqG8ALDFv4vLxyquxX6dYcjt7iGrMU9+3wCdtRmvkapuDLjG52EDTuPDlc6dk3dncTeiKVfe2pu",
	"6x3MCutbj3c3ZikeUGl/wimcIYzIOwO9PUI//KRtY587LHrDhx39RWwNfE1gs0MN3l3BPj38Ut0SPJgK",
	"3BZ7gg19gaK3xeTlwGDrWE+tf9gJ54qgUfPN/u2FHTPOZuGPfcL5TuUIXRWW1gaceVk5X/edLQ7ZVP2r",
	"mwcdvPZ/1vOjvW7zGSTdjgMc8cKPuaXs3/kRN5o8b120cx5YxffANO6YWucbVevoTwhNddGT4eoaHtNX",
	"fQRkywfmFUarYshcVgqdN5rB1MrBdw39an/4KEZ+b90kHx3HJG9lIoeqTY2aWyam7OtGo889LrHjlEFL",
	"4IatyO75hyabr91WJc+is2iKCzJdP4yuL6//EwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
