// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CameraStatus.
const (
	Offline CameraStatus = "offline"
	Online  CameraStatus = "online"
	Unknown CameraStatus = "unknown"
)

// Valid indicates whether the value is a known member of the CameraStatus enum.
func (e CameraStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for CreateUserRequestRole.
const (
	CreateUserRequestRoleAdmin    CreateUserRequestRole = "admin"
	CreateUserRequestRoleOperator CreateUserRequestRole = "operator"
	CreateUserRequestRoleViewer   CreateUserRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the CreateUserRequestRole enum.
func (e CreateUserRequestRole) Valid() bool {
	switch e {
	case CreateUserRequestRoleAdmin:
		return true
	case CreateUserRequestRoleOperator:
		return true
	case CreateUserRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for EventSeverity.
const (
	Critical EventSeverity = "critical"
	Info     EventSeverity = "info"
	Warning  EventSeverity = "warning"
)

// Valid indicates whether the value is a known member of the EventSeverity enum.
func (e EventSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for StreamProfileRole.
const (
	Live   StreamProfileRole = "live"
	Record StreamProfileRole = "record"
)

// Valid indicates whether the value is a known member of the StreamProfileRole enum.
func (e StreamProfileRole) Valid() bool {
	switch e {
	case Live:
		return true
	case Record:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusHealthStatus.
const (
	SystemStatusHealthStatusDegraded SystemStatusHealthStatus = "degraded"
	SystemStatusHealthStatusOk       SystemStatusHealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the SystemStatusHealthStatus enum.
func (e SystemStatusHealthStatus) Valid() bool {
	switch e {
	case SystemStatusHealthStatusDegraded:
		return true
	case SystemStatusHealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for UserPublicRole.
const (
	UserPublicRoleAdmin    UserPublicRole = "admin"
	UserPublicRoleOperator UserPublicRole = "operator"
	UserPublicRoleViewer   UserPublicRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserPublicRole enum.
func (e UserPublicRole) Valid() bool {
	switch e {
	case UserPublicRoleAdmin:
		return true
	case UserPublicRoleOperator:
		return true
	case UserPublicRoleViewer:
		return true
	default:
		return false
	}
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	SetupRequired bool        `json:"setupRequired"`
	User          *UserPublic `json:"user,omitempty"`
}

// Camera defines model for Camera.
type Camera struct {
	CreatedAt time.Time `json:"createdAt"`

	// Driver Camera driver identifier (e.g. generic-rtsp)
	Driver  string `json:"driver"`
	Enabled bool   `json:"enabled"`

	// Host Display host or primary RTSP base
	Host           string             `json:"host"`
	Id             openapi_types.UUID `json:"id"`
	Name           string             `json:"name"`
	Status         CameraStatus       `json:"status"`
	StreamProfiles []StreamProfile    `json:"streamProfiles"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// CameraStatus defines model for Camera.Status.
type CameraStatus string

// CoverageBar Timeline UI aggregation bar (can match segments for phase 4)
type CoverageBar struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

// CreateCameraRequest defines model for CreateCameraRequest.
type CreateCameraRequest struct {
	Driver  *string `json:"driver,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`
	Host    string  `json:"host"`

	// LiveRtspUrl Live stream RTSP URL; if omitted, may be derived later
	LiveRtspUrl *string `json:"liveRtspUrl,omitempty"`
	Name        string  `json:"name"`
	Password    *string `json:"password,omitempty"`

	// RecordRtspUrl Record stream RTSP URL
	RecordRtspUrl *string `json:"recordRtspUrl,omitempty"`
	Username      *string `json:"username,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Password string                `json:"password"`
	Role     CreateUserRequestRole `json:"role"`
	Username string                `json:"username"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// DiscoverCameraStreamsRequest defines model for DiscoverCameraStreamsRequest.
type DiscoverCameraStreamsRequest struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`

	// Xaddr ONVIF device service URL returned by discovery
	Xaddr string `json:"xaddr"`
}

// DiscoverCameraStreamsResult defines model for DiscoverCameraStreamsResult.
type DiscoverCameraStreamsResult struct {
	LiveRtspUrl   string `json:"liveRtspUrl"`
	RecordRtspUrl string `json:"recordRtspUrl"`
}

// DiscoverCamerasRequest defines model for DiscoverCamerasRequest.
type DiscoverCamerasRequest struct {
	// Password Camera or NVR password; used only for this discovery request
	Password *string `json:"password,omitempty"`

	// Username Camera or NVR username or account ID
	Username string `json:"username"`
}

// DiscoverResult defines model for DiscoverResult.
type DiscoverResult struct {
	Cameras []DiscoveredCamera `json:"cameras"`
}

// DiscoveredCamera defines model for DiscoveredCamera.
type DiscoveredCamera struct {
	// Host Host and optional port reported by the device
	Host string `json:"host"`

	// Id Stable identifier for this discovery result
	Id string `json:"id"`

	// LiveRtspUrl Authenticated RTSP URL without embedded credentials
	LiveRtspUrl string `json:"liveRtspUrl"`

	// Name Camera name or discovered NVR channel
	Name string `json:"name"`

	// RecordRtspUrl Authenticated record RTSP URL without embedded credentials
	RecordRtspUrl string `json:"recordRtspUrl"`

	// Xaddr ONVIF device service URL or discovered RTSP URL
	Xaddr string `json:"xaddr"`
}

// DiskInfo defines model for DiskInfo.
type DiskInfo struct {
	FreeBytes   int64   `json:"freeBytes"`
	Path        string  `json:"path"`
	TotalBytes  int64   `json:"totalBytes"`
	UsedBytes   int64   `json:"usedBytes"`
	UsedPercent float32 `json:"usedPercent"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Acknowledged bool                    `json:"acknowledged"`
	CameraId     *string                 `json:"cameraId,omitempty"`
	CreatedAt    time.Time               `json:"createdAt"`
	EndedAt      *time.Time              `json:"endedAt,omitempty"`
	Id           string                  `json:"id"`
	Message      string                  `json:"message"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Severity     EventSeverity           `json:"severity"`
	StartedAt    time.Time               `json:"startedAt"`
	Title        string                  `json:"title"`
	Type         string                  `json:"type"`
}

// EventSeverity defines model for Event.Severity.
type EventSeverity string

// EventList defines model for EventList.
type EventList struct {
	Events []Event `json:"events"`
}

// GDriveArchiveRequest defines model for GDriveArchiveRequest.
type GDriveArchiveRequest struct {
	// Limit Max segments to archive in this batch (default 50)
	Limit *int `json:"limit,omitempty"`
}

// GDriveArchiveResponse defines model for GDriveArchiveResponse.
type GDriveArchiveResponse struct {
	Failed   int `json:"failed"`
	Skipped  int `json:"skipped"`
	Uploaded int `json:"uploaded"`
}

// GDriveConfigurationRequest defines model for GDriveConfigurationRequest.
type GDriveConfigurationRequest struct {
	// ClientId OAuth web client ID from Google Cloud Console
	ClientId string `json:"clientId"`

	// ClientSecret OAuth web client secret; encrypted at rest and never returned
	ClientSecret *string `json:"clientSecret,omitempty"`

	// RedirectUrl Authorized OAuth redirect URI configured in Google Cloud Console
	RedirectUrl string `json:"redirectUrl"`
}

// GDriveConnectResponse defines model for GDriveConnectResponse.
type GDriveConnectResponse struct {
	// AuthorizationUrl Google OAuth consent URL
	AuthorizationUrl string `json:"authorizationUrl"`
}

// GDriveStatus defines model for GDriveStatus.
type GDriveStatus struct {
	// AccountEmail Connected Google account email; returned only to administrators
	AccountEmail *string `json:"accountEmail,omitempty"`

	// Configured True when Google OAuth client details are saved in the dashboard or supplied by environment, and NVR_SECRETS_KEY is set
	Configured bool `json:"configured"`

	// Connected True when stored credentials can be decrypted
	Connected   bool       `json:"connected"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`

	// ConnectionError Recoverable stored-credential problem; reconnecting resolves it
	ConnectionError *string `json:"connectionError,omitempty"`
	FolderId        *string `json:"folderId,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LiveStream defines model for LiveStream.
type LiveStream struct {
	// CameraId Camera ID for this live session
	CameraId string `json:"cameraId"`

	// ExpiresAt When the stream token expires
	ExpiresAt time.Time `json:"expiresAt"`

	// HlsUrl Full or relative URL for HLS playback
	HlsUrl string `json:"hlsUrl"`

	// Token Stream token to pass as query `?token=` or header as documented
	Token string `json:"token"`

	// WhepUrl Full or relative URL for WHEP playback
	WhepUrl string `json:"whepUrl"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PatchSettingsRequest defines model for PatchSettingsRequest.
type PatchSettingsRequest struct {
	RecordingEnabled *bool `json:"recordingEnabled,omitempty"`

	// RecordingsDir Absolute or relative path on the NVR server for new recordings.
	RecordingsDir *string `json:"recordingsDir,omitempty"`
	RetentionDays *int    `json:"retentionDays,omitempty"`
	SiteName      *string `json:"siteName,omitempty"`
}

// PlaybackRequest defines model for PlaybackRequest.
type PlaybackRequest struct {
	// DurationSec Playback window length in seconds
	DurationSec *float32  `json:"durationSec,omitempty"`
	Start       time.Time `json:"start"`
}

// PlaybackSession defines model for PlaybackSession.
type PlaybackSession struct {
	CameraId    string    `json:"cameraId"`
	ExpiresAt   time.Time `json:"expiresAt"`
	PlaybackUrl string    `json:"playbackUrl"`
	Token       string    `json:"token"`
}

// ProbeCameraRequest defines model for ProbeCameraRequest.
type ProbeCameraRequest struct {
	Password *string `json:"password,omitempty"`
	RtspUrl  string  `json:"rtspUrl"`
	Username *string `json:"username,omitempty"`
}

// ProbeResult defines model for ProbeResult.
type ProbeResult struct {
	Codec *string `json:"codec,omitempty"`
	Error *string `json:"error,omitempty"`

	// H265 True if codec looks like hevc/h265
	H265      bool `json:"h265"`
	Height    *int `json:"height,omitempty"`
	Reachable bool `json:"reachable"`
	Width     *int `json:"width,omitempty"`
}

// RecordingList defines model for RecordingList.
type RecordingList struct {
	Coverage   []CoverageBar      `json:"coverage"`
	Recordings []RecordingSegment `json:"recordings"`
}

// RecordingSegment defines model for RecordingSegment.
type RecordingSegment struct {
	CameraId    string  `json:"cameraId"`
	Codec       *string `json:"codec,omitempty"`
	DurationSec float32 `json:"durationSec"`
	Id          string  `json:"id"`

	// Path Relative storage path
	Path         string    `json:"path"`
	SizeBytes    int64     `json:"sizeBytes"`
	StartedAt    time.Time `json:"startedAt"`
	ThumbnailUrl *string   `json:"thumbnailUrl,omitempty"`
}

// Settings defines model for Settings.
type Settings struct {
	// RecordingEnabled When false, MediaMTX continuous recording is disabled for all cameras.
	RecordingEnabled bool `json:"recordingEnabled"`

	// RecordingsDir Absolute or relative path on the NVR server where recordings are stored.
	RecordingsDir string `json:"recordingsDir"`
	RetentionDays int    `json:"retentionDays"`
	SiteName      string `json:"siteName"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// StreamProfile defines model for StreamProfile.
type StreamProfile struct {
	Codec   *string           `json:"codec,omitempty"`
	Height  *int              `json:"height,omitempty"`
	Id      string            `json:"id"`
	Role    StreamProfileRole `json:"role"`
	RtspUrl string            `json:"rtspUrl"`
	Width   *int              `json:"width,omitempty"`
}

// StreamProfileRole defines model for StreamProfile.Role.
type StreamProfileRole string

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	Cameras struct {
		Enabled int `json:"enabled"`
		Online  int `json:"online"`
		Total   int `json:"total"`
	} `json:"cameras"`
	Commit string   `json:"commit"`
	Disk   DiskInfo `json:"disk"`
	Health struct {
		Status SystemStatusHealthStatus `json:"status"`
	} `json:"health"`
	RetentionDays int    `json:"retentionDays"`
	Version       string `json:"version"`
}

// SystemStatusHealthStatus defines model for SystemStatus.Health.Status.
type SystemStatusHealthStatus string

// UpdateCameraRequest defines model for UpdateCameraRequest.
type UpdateCameraRequest struct {
	Driver        *string `json:"driver,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
	Host          *string `json:"host,omitempty"`
	LiveRtspUrl   *string `json:"liveRtspUrl,omitempty"`
	Name          *string `json:"name,omitempty"`
	Password      *string `json:"password,omitempty"`
	RecordRtspUrl *string `json:"recordRtspUrl,omitempty"`
	Username      *string `json:"username,omitempty"`
}

// UserPublic defines model for UserPublic.
type UserPublic struct {
	Id       string         `json:"id"`
	Role     UserPublicRole `json:"role"`
	Username string         `json:"username"`
}

// UserPublicRole defines model for UserPublic.Role.
type UserPublicRole string

// Version defines model for Version.
type Version struct {
	Commit  string `json:"commit"`
	Version string `json:"version"`
}

// ListCameraRecordingsParams defines parameters for ListCameraRecordings.
type ListCameraRecordingsParams struct {
	// From Range start (inclusive)
	From time.Time `form:"from" json:"from"`

	// To Range end (inclusive)
	To time.Time `form:"to" json:"to"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Cursor — return events before this timestamp
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// CameraId Filter by camera ID
	CameraId *openapi_types.UUID `form:"cameraId,omitempty" json:"cameraId,omitempty"`

	// Type Filter by event type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// UnacknowledgedOnly When true, only return unacknowledged events
	UnacknowledgedOnly *bool `form:"unacknowledgedOnly,omitempty" json:"unacknowledgedOnly,omitempty"`
}

// GetGDriveCallbackParams defines parameters for GetGDriveCallback.
type GetGDriveCallbackParams struct {
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	State            *string `form:"state,omitempty" json:"state,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthSetupJSONRequestBody defines body for PostAuthSetup for application/json ContentType.
type PostAuthSetupJSONRequestBody = SetupRequest

// CreateCameraJSONRequestBody defines body for CreateCamera for application/json ContentType.
type CreateCameraJSONRequestBody = CreateCameraRequest

// DiscoverCamerasJSONRequestBody defines body for DiscoverCameras for application/json ContentType.
type DiscoverCamerasJSONRequestBody = DiscoverCamerasRequest

// DiscoverCameraStreamsJSONRequestBody defines body for DiscoverCameraStreams for application/json ContentType.
type DiscoverCameraStreamsJSONRequestBody = DiscoverCameraStreamsRequest

// ProbeCameraJSONRequestBody defines body for ProbeCamera for application/json ContentType.
type ProbeCameraJSONRequestBody = ProbeCameraRequest

// UpdateCameraJSONRequestBody defines body for UpdateCamera for application/json ContentType.
type UpdateCameraJSONRequestBody = UpdateCameraRequest

// PostCameraPlaybackJSONRequestBody defines body for PostCameraPlayback for application/json ContentType.
type PostCameraPlaybackJSONRequestBody = PlaybackRequest

// PatchSettingsJSONRequestBody defines body for PatchSettings for application/json ContentType.
type PatchSettingsJSONRequestBody = PatchSettingsRequest

// PostGDriveArchiveJSONRequestBody defines body for PostGDriveArchive for application/json ContentType.
type PostGDriveArchiveJSONRequestBody = GDriveArchiveRequest

// PutGDriveConfigurationJSONRequestBody defines body for PutGDriveConfiguration for application/json ContentType.
type PutGDriveConfigurationJSONRequestBody = GDriveConfigurationRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostAuthLogin Log in
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// PostAuthLogout Log out
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// GetAuthMe Current user
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// PostAuthSetup Initial admin setup
	// (POST /auth/setup)
	PostAuthSetup(w http.ResponseWriter, r *http.Request)
	// GetAuthStatus Authentication status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// ListCameras List cameras
	// (GET /cameras)
	ListCameras(w http.ResponseWriter, r *http.Request)
	// CreateCamera Create camera
	// (POST /cameras)
	CreateCamera(w http.ResponseWriter, r *http.Request)
	// DiscoverCameras Discover authenticated RTSP and ONVIF cameras
	// (POST /cameras/discover)
	DiscoverCameras(w http.ResponseWriter, r *http.Request)
	// DiscoverCameraStreams Discover authenticated RTSP streams
	// (POST /cameras/discover/streams)
	DiscoverCameraStreams(w http.ResponseWriter, r *http.Request)
	// ProbeCamera Probe RTSP stream
	// (POST /cameras/probe)
	ProbeCamera(w http.ResponseWriter, r *http.Request)
	// DeleteCamera Delete camera
	// (DELETE /cameras/{id})
	DeleteCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetCamera Get camera
	// (GET /cameras/{id})
	GetCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateCamera Update camera
	// (PATCH /cameras/{id})
	UpdateCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostCameraLive Start or get live stream endpoints
	// (POST /cameras/{id}/live)
	PostCameraLive(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostCameraPlayback Start playback session
	// (POST /cameras/{id}/playback)
	PostCameraPlayback(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListCameraRecordings List camera recordings
	// (GET /cameras/{id}/recordings)
	ListCameraRecordings(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCameraRecordingsParams)
	// GetCameraSnapshot Camera snapshot
	// (GET /cameras/{id}/snapshot)
	GetCameraSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListEvents List events
	// (GET /events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// AcknowledgeEvent Acknowledge an event
	// (POST /events/{id}/acknowledge)
	AcknowledgeEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetSettings Get settings
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// PatchSettings Update settings
	// (PATCH /settings)
	PatchSettings(w http.ResponseWriter, r *http.Request)
	// PostGDriveArchive Archive recordings to Google Drive
	// (POST /storage/gdrive/archive)
	PostGDriveArchive(w http.ResponseWriter, r *http.Request)
	// GetGDriveCallback Google Drive OAuth callback
	// (GET /storage/gdrive/callback)
	GetGDriveCallback(w http.ResponseWriter, r *http.Request, params GetGDriveCallbackParams)
	// PutGDriveConfiguration Save Google Drive OAuth configuration
	// (PUT /storage/gdrive/configuration)
	PutGDriveConfiguration(w http.ResponseWriter, r *http.Request)
	// PostGDriveConnect Begin Google Drive OAuth connect
	// (POST /storage/gdrive/connect)
	PostGDriveConnect(w http.ResponseWriter, r *http.Request)
	// DeleteGDriveDisconnect Disconnect Google Drive
	// (DELETE /storage/gdrive/disconnect)
	DeleteGDriveDisconnect(w http.ResponseWriter, r *http.Request)
	// GetGDriveStatus Google Drive connection status
	// (GET /storage/gdrive/status)
	GetGDriveStatus(w http.ResponseWriter, r *http.Request)
	// GetSystemDisk Disk usage
	// (GET /system/disk)
	GetSystemDisk(w http.ResponseWriter, r *http.Request)
	// GetSystemStatus System status overview
	// (GET /system/status)
	GetSystemStatus(w http.ResponseWriter, r *http.Request)

	// (GET /system/version)
	GetVersion(w http.ResponseWriter, r *http.Request)
	// ListUsers List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// CreateUser Create user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Delete user
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PostAuthLogin Log in
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostAuthLogout Log out
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthMe Current user
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostAuthSetup Initial admin setup
// (POST /auth/setup)
func (_ Unimplemented) PostAuthSetup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthStatus Authentication status
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCameras List cameras
// (GET /cameras)
func (_ Unimplemented) ListCameras(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCamera Create camera
// (POST /cameras)
func (_ Unimplemented) CreateCamera(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DiscoverCameras Discover authenticated RTSP and ONVIF cameras
// (POST /cameras/discover)
func (_ Unimplemented) DiscoverCameras(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DiscoverCameraStreams Discover authenticated RTSP streams
// (POST /cameras/discover/streams)
func (_ Unimplemented) DiscoverCameraStreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ProbeCamera Probe RTSP stream
// (POST /cameras/probe)
func (_ Unimplemented) ProbeCamera(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCamera Delete camera
// (DELETE /cameras/{id})
func (_ Unimplemented) DeleteCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCamera Get camera
// (GET /cameras/{id})
func (_ Unimplemented) GetCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCamera Update camera
// (PATCH /cameras/{id})
func (_ Unimplemented) UpdateCamera(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostCameraLive Start or get live stream endpoints
// (POST /cameras/{id}/live)
func (_ Unimplemented) PostCameraLive(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostCameraPlayback Start playback session
// (POST /cameras/{id}/playback)
func (_ Unimplemented) PostCameraPlayback(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCameraRecordings List camera recordings
// (GET /cameras/{id}/recordings)
func (_ Unimplemented) ListCameraRecordings(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCameraRecordingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCameraSnapshot Camera snapshot
// (GET /cameras/{id}/snapshot)
func (_ Unimplemented) GetCameraSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEvents List events
// (GET /events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AcknowledgeEvent Acknowledge an event
// (POST /events/{id}/acknowledge)
func (_ Unimplemented) AcknowledgeEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSettings Get settings
// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PatchSettings Update settings
// (PATCH /settings)
func (_ Unimplemented) PatchSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostGDriveArchive Archive recordings to Google Drive
// (POST /storage/gdrive/archive)
func (_ Unimplemented) PostGDriveArchive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetGDriveCallback Google Drive OAuth callback
// (GET /storage/gdrive/callback)
func (_ Unimplemented) GetGDriveCallback(w http.ResponseWriter, r *http.Request, params GetGDriveCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PutGDriveConfiguration Save Google Drive OAuth configuration
// (PUT /storage/gdrive/configuration)
func (_ Unimplemented) PutGDriveConfiguration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostGDriveConnect Begin Google Drive OAuth connect
// (POST /storage/gdrive/connect)
func (_ Unimplemented) PostGDriveConnect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteGDriveDisconnect Disconnect Google Drive
// (DELETE /storage/gdrive/disconnect)
func (_ Unimplemented) DeleteGDriveDisconnect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetGDriveStatus Google Drive connection status
// (GET /storage/gdrive/status)
func (_ Unimplemented) GetGDriveStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSystemDisk Disk usage
// (GET /system/disk)
func (_ Unimplemented) GetSystemDisk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSystemStatus System status overview
// (GET /system/status)
func (_ Unimplemented) GetSystemStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /system/version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUsers List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateUser Create user
// (POST /users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteUser Delete user
// (DELETE /users/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSetup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCameras operation middleware
func (siw *ServerInterfaceWrapper) ListCameras(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCameras(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCamera operation middleware
func (siw *ServerInterfaceWrapper) CreateCamera(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCamera(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverCameras operation middleware
func (siw *ServerInterfaceWrapper) DiscoverCameras(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverCameras(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverCameraStreams operation middleware
func (siw *ServerInterfaceWrapper) DiscoverCameraStreams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverCameraStreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProbeCamera operation middleware
func (siw *ServerInterfaceWrapper) ProbeCamera(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProbeCamera(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCamera operation middleware
func (siw *ServerInterfaceWrapper) DeleteCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCamera operation middleware
func (siw *ServerInterfaceWrapper) GetCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCamera operation middleware
func (siw *ServerInterfaceWrapper) UpdateCamera(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCamera(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCameraLive operation middleware
func (siw *ServerInterfaceWrapper) PostCameraLive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCameraLive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCameraPlayback operation middleware
func (siw *ServerInterfaceWrapper) PostCameraPlayback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCameraPlayback(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCameraRecordings operation middleware
func (siw *ServerInterfaceWrapper) ListCameraRecordings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCameraRecordingsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCameraRecordings(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCameraSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetCameraSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCameraSnapshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cameraId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cameraId", r.URL.Query(), &params.CameraId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cameraId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cameraId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unacknowledgedOnly" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unacknowledgedOnly", r.URL.Query(), &params.UnacknowledgedOnly, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unacknowledgedOnly"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unacknowledgedOnly", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcknowledgeEvent operation middleware
func (siw *ServerInterfaceWrapper) AcknowledgeEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcknowledgeEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGDriveArchive operation middleware
func (siw *ServerInterfaceWrapper) PostGDriveArchive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGDriveArchive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGDriveCallback operation middleware
func (siw *ServerInterfaceWrapper) GetGDriveCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGDriveCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error_description"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGDriveCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutGDriveConfiguration operation middleware
func (siw *ServerInterfaceWrapper) PutGDriveConfiguration(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutGDriveConfiguration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGDriveConnect operation middleware
func (siw *ServerInterfaceWrapper) PostGDriveConnect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGDriveConnect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGDriveDisconnect operation middleware
func (siw *ServerInterfaceWrapper) DeleteGDriveDisconnect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGDriveDisconnect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGDriveStatus operation middleware
func (siw *ServerInterfaceWrapper) GetGDriveStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGDriveStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemDisk operation middleware
func (siw *ServerInterfaceWrapper) GetSystemDisk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemDisk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/version", wrapper.GetVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/setup", wrapper.PostAuthSetup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras", wrapper.ListCameras)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras", wrapper.CreateCamera)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/discover", wrapper.DiscoverCameras)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/discover/streams", wrapper.DiscoverCameraStreams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/probe", wrapper.ProbeCamera)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cameras/{id}", wrapper.DeleteCamera)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}", wrapper.GetCamera)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/cameras/{id}", wrapper.UpdateCamera)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/{id}/live", wrapper.PostCameraLive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}/snapshot", wrapper.GetCameraSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cameras/{id}/recordings", wrapper.ListCameraRecordings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cameras/{id}/playback", wrapper.PostCameraPlayback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{id}/acknowledge", wrapper.AcknowledgeEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/disk", wrapper.GetSystemDisk)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/status", wrapper.GetSystemStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/settings", wrapper.PatchSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/gdrive/status", wrapper.GetGDriveStatus)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/storage/gdrive/configuration", wrapper.PutGDriveConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/storage/gdrive/connect", wrapper.PostGDriveConnect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/gdrive/callback", wrapper.GetGDriveCallback)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/storage/gdrive/disconnect", wrapper.DeleteGDriveDisconnect)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/storage/gdrive/archive", wrapper.PostGDriveArchive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H19b9w2k/hXIfT7AecAG9tp0+IeB4eDa7uJr25jeOP0DnXQcqXZXdYSqYekdrNPYeA+xH3C+yQHvkmU",
	"RGm1dnYdP8lfiS2JHM77DGfGf0Uxy3JGgUoRHf0ViXgOGdb/PS7kfCyxLPRPOWc5cEnAvAayyK/g7wXh",
	"kKhfyFUO0VE0YSwFTKO7UVQI4OrJ/+cwjY6i/3dQbXRgdzm4FsAvi0lK4ujubhTxcsHfGjt8GLkd2ORP",
	"iKXa4ARnwHEbtpgDlpAcS/XDlPEMy+goSrCE55JkEJVLCckJnamlEk4WBtoERMxJLgmj0ZHdApnHiCRA",
	"JZkS4GgP9mf7aAYUOImfcynyZ6F1geJJ2oWgOROyveUpEXmKV0g9RYyjnJMM8xW6eje+RBMsgvCTpHbW",
	"oiBJ6DWKM/BgqR6IkswJTHGR6kXoLWVLGqlTFJkiCaMpoWp/Np3a/7mXPoxCi3LA2SVnU5IayhAJmVjH",
	"E2P/M7WOXRhzjleasfJkM/o2OEvjRqOiJHxFKUuWEiWtY4w8/vJhCXIoWwDHM/gBB3jrHclAYRFdnyM8",
	"m3GYYfUETTBHezGmKMMyniMBs0zhB00VM8yxAPRS8Vqd54Emw7ldSMzvizzz7UhvGDyyRo6RGyW9YHi8",
	"Dq0vbo7dfFlaI0rlR5IXMOqRrNYiKVnAlRT5NU/bBLkgC0CG2kbarq8uXiEyRSwjUkIyQhleoQmgBBT8",
	"CUqx1LzTKWcZoRdAZ3IeHb0IvJZjIZaMJ0FQOcSMJ53AXunHTXBDwCg93CH4DdpamdDY66at0tmdlPWP",
	"5J3+XwNwcZaCYV2jXXCSEaVt1HJYMoXYBYEl8KBy8U/Vi+bGGcvvPPRbWEJHPiUiVkJsGNqoJrHp6VtA",
	"jaIlJxLe0nRlmHiTA42ijzhJAgrl7S/vz39ECSxIDEgA1/9eX10gDrLgFBI0WaHEHmgVjTx7wclawTeb",
	"joII3ABzQgtuE3ENuewHLCAbG53E36y51vqTDKN+0I1gHP3y/gq5916hQkCCGE1XWrnLOREVfRC3+4we",
	"xEp9gLj31M84jllBJTo/XbPhEIHqw2IXC8QGu4PdBLceJNYPbHkKDUDdBn3AlYu1wAs7a2+Uk4Zpgpj+",
	"DU5RzrhEHNQ/RuDkHKxMdjtu9UXHUlk639sMcodG42hDG6d8erVsrLyW0mygJZFzVkgE2QSSBBIUc9Db",
	"41SsVRSVvQsym+OwpMSxZr54jimFdJB4953BvPzJjrKpbq0fzLPDG6kk3yW1/qfTt/fQVrfndMraLDzl",
	"AD+spP3BgUeo/P5lBSChEmbAjXuiFEDANZFM4nSTlZSe2/T9S+AxUN+No0U2Uc8buNNg1oDyNxx5x64v",
	"HELeGeeMB3QTS8JxE7j3+8lrXgtuuLBnrG+IYxVWpZDMuoJHo83O9VNapKlSGQ2HuALzHhEx0KT3g7V7",
	"krBbm4EQeAYdzyROsNTaFycJMSr10sNMba8KiwIWwIlc+e4kUTIwipaYU2MnY06Uzkg7YlXMN8SQJDIN",
	"n8P84q8hMq9f8Q7glq0Q5cM2qjOGT9hO5rogIV8FFi7hM8jYGjZdZ2HtoiFQXp+qkOmYx3Olzro8qJRk",
	"RNYivO8ORw1N/DP+WMXEkiFs1kSEGhM50VHznl0BfXeoguUMfySZ4gu1Xkao+eFFW/fcrYdd5IwKCKhX",
	"TOqpHk+hiVuS510PizxlOAk/bTpb7tWR265auxvtJ4xOyazgOr/Qifw4JUDlecAheassLlrCBJl30Pkp",
	"mnKWodeMzVJAJykrEnTCqGCGdfvDF7PIGGIOcsBmQr/4CgGN+SpXJh8rD8s6XlRJThnh3MNZ5pAQDrHs",
	"dDUYJ/+ABBm43Nvo+uocxRavkCju60DGRn5ASYMGlupg9lKaQiy7mRTbA2lWCB7ZHsMcN1arUBlOLTRg",
	"by3dDWZXVtkGIWcZJgHI7OEgcah2MQuo919VYa6OqJRqSJSoC6nTCSKkwysKBvJzvAC0nENJWYsSw5UJ",
	"SExSgTAHJPDCsID29bGYTxjmiXINRZHnKTGBANAF4YwqxTXSrPvL+6vfx2cnV2fvxr//dPZfiAgkwHPp",
	"fWvvjt4HppCM1/1dFGNqElZWdPoX38T62Y8Io6XP1E5QLYDrUMZA9ryCDOWcTVLIXmn33axEZ0qqWboA",
	"gUgwspmyNAF+nqy3rR5dfeSFOPIN4NT4uY0bjpJHy/T3baSM0YxrDfxhQKZULRDa80LLAAecdcXB591Z",
	"BKV8XTyY6pQlCKHeCHlxH3PCQRwH9OyvimUUw9oUomS3QJH9wNdbvWwwT0VQi/xYpKkSAA4plgpIFSsp",
	"sN9cjFGe4tUEx7dBr0qBEYqJPSAl0zkUhAX6e6GC4T/+XT/4tz/UlnPACXD1MGFxocQNgpchyznkm8H+",
	"65uzyx7gg/kGrcvdViW+3Dl9CgUZhc0IfXC68ROnS0OAXiqvawxSiXF3hsxEr4TOzvruxcq3xCkJKJbj",
	"iWBpIaFGIhUEImYY+pf3VzpEt4kTCktULbkfTjhIpZcYPcUrYVHU6SKOIkEk/NKZUW/jxnJM93WIdc3G",
	"ENec3+9bzq9bCi0JTdgSpZqOyvQIpUcTz8i5aPlTXPd86DnV2GqfXkXWr5iGqRoneFZmuzXHYLH0Vxwq",
	"kZecTdZdb/Xf61RprQ1ktv9MvCcfpAHuTLqyxPDc4MzGKJp/8/13HW4ImSK9IkoZu1XW6RbQHBbxgf4m",
	"eFMHZDaX4biIA47nJscQUhNLktTyU10xU7WMhT2EpSunIMLhcmwvcgcHzP7Nb+AKu9JHg1csIRyb4Hdt",
	"NO7tMaoO0Ht4t/RmstzNRA3F1tJMHTkil3hsOpRW1ytvEs+Mzg9eb5N/bJTnvE/uZ15kE4pJaiV5TTYs",
	"lPnx9JCf4PFR5h/FYiVEPmd2h9nbgBc4xamAEfoZEoJ/fvefKuqThBasEJXhROb2QS+jzSpOU2SvVPaD",
	"ov0JzfhyDhw8I26iLh1UDLPnm9rwuhz5i3lfNo84auO7g1ymsOmhF+jb9unqhTjdtmNtKrhPyXeogGZx",
	"gAp0SgQHM7ieXW27+gNNBSlrAUa9NnW8EhKyriyGd5PZLNJper0eImxxVfCZvtsYAL95zy9msquGDhGz",
	"zGZb23qbiNsB96/mnkkTePcx9AAZXwB3rmn/Nu7FEinlkSwuRiVRmxuHQLvWRWGDa6DuVzW47t53N0VJ",
	"GzqtbVRVBaAtDA1UDfevGxpgpT1d2Vkj9L5is6aG7JSw+7NmGwJ9ARYXnMjVWAmn25zdEjguQq6UjdmQ",
	"eQcRIQqdNkUpmxGqE5fKSCnbStT75j13RX0U0QX/vZV1wjn5CZQbqrS6vYBuJXAlx7HU/sNrhvYYzslz",
	"ZUdmQJ/pnGiO41s8A3Ggn5hU6x7Lgaqf1UZmvWf75U3ZUaQchePL88jDanS4/2L/UKtV8210FH2rf2X8",
	"KI2hA1zI+YE+sqZdsMLDLzYQurigKpsxABtx2b+hbykSRRyDECOEXVbO4fgPD2d/2FQvWhCMxiCfn+h3",
	"9m8qNiaMKm87umRCKhB0IigyrAFC/sCSlSEyldZhx3meKigJowd/CsNaRlev0+S1JNNdnQHLSxJzoaDx",
	"9s3h4Sfbu1YAfjfqq/R41USpSZabdJ8GrELlWpavkUM5dSW0TXFUUL38hCc26fLAYc/pAqckcXVfaKJo",
	"rDd/sbvN/WIZrViKLMN8FR1FF2yGNAtKrEINc98TfVAvlYLECtktSWc0EdqxjwvOzcWeIYkSozgFzM3j",
	"uqQYeu33CYbatcWiLwP1vWw2U2qukIGjmUW6zmbsxSx0X3mlb50M6LhWmaT0hE3Vtw7dPtBr0Of5GaJH",
	"E7e3P+2M365pDVc1IxYd/VY3X799uPvg0+vE4lJ3mHQTTduwbn401cyGcFPChTT3hYZs+kKNMv2DQPCR",
	"CLllDa/Dwi1p+FrIOUjDv9gRy6mnyFaxfLkK/m87EDjNyDjlgJOVYehXxstDlEmE05QtnRyWgnZOib6t",
	"NYIhLId2ylsZ7fUqyuUc5Bw4InZxAwQRyPGkNgghQ6Elk0zrarZTk45dA8/WtKm3S4c2rWHT82bUacoG",
	"owA+vRSCxWX9iBdEyBMvIn3AAR9Whf3g2uuna4UUDVCVFnBULI+qYmlreOrE81uktqTwQ11YO9b7jjPa",
	"WLd1DFbrR1+Ef/0wf0djyvJakNU8nXHgytG7PZ9xjK3DqkLnORPyXwRKWYxTREEuGb/VbqupeXe/WZAE",
	"GJIcU6Hb4bi4oUpRn+J5gZ8rXGBJJimYGnhb3S/20bs5VGVQsd9/ckP9UiXMwfTD6C1U4G+LuDy8IcDx",
	"3K+3NwX5+zf0tGyMSBgIbdJy4EKLqLeJvmsQRSpFyBVrNPpsSTY72ol2HHg32nECLFv1xJRableiWmmI",
	"GntkRAibP3scoR1F3+3i+BUz2yLfjbSF+7oRjWqxVAJrxLrPcIW0yYEpExNDM2VKcpGA1BRs+ntqILh1",
	"BokUBjKz/A29vroQ++gkpBjqjXJOjavV1CueyEOyXrptQ+JOZLzRNvpIkh5qxOwXe48wSNHlMeW/tEeO",
	"7k40noIB7xNJUTJivyDmnE2gW/p0mY9AmFadcFNt7XTxC0mJXGlRseR0rTZlu5z2xgidIWzFNJByq0qf",
	"tiQ2geKqHQuLXy0V4AL92PVefnVc1/G9QZfH5mu5/C+S3BnmTkFCO3Y61b/3mHBd0tdNcNHfJY/pOrw0",
	"4O1EcypjOGUF3VRPaSz1BRqjcD7iNcgumhzuIKJ8zJTBkyDsa5D9VM0xxxlInWf9rbPxwN0H28o7exts",
	"qmZqKtrPt66ZSqQAzbGM522u8usotmRxQqUaOzY5axMldsbQF2pvnoR8GTYamqFRRu5AV7Tpgr9Hlbyg",
	"M+lS9b++Obs88Dt2dBhgQi4k5ozL56mehFTrISqvPI0feUMvsTDpJvM80LazxxoNO25yRgYJwSjFK+DP",
	"um7PDJIuXIXglsTU69kKsI8/OwpokjNCpXhcofl2+/v+yPiEJAnQRxTTHd2fOT/SlkBvph7GEnM9zG8G",
	"0vbsNVllkM4oe88+U73hrtTryqFUHu4ezwSmMeMJJDavrEvgdfgptdzPyAIokiSDfqm/rLrxthKQNlq3",
	"dh2NNnqsQhFpA7lfoKHekQYoMa3vyxeYmKL3eyiCpkAME/56z1DvFXvVtVFOytBFVrYJCE0wN/MkXbJH",
	"p4FsA3sleohjOgsKYHX/fOV3GfXqpCu1mBF0tEdonBaCLOCZ01DaJahU1JSzbJiS6m1mDAMBNBkAgmQP",
	"B+DDFrVDvWctwLHlCyglQpri1bIR7KtDP/ByH9Ua6T634LmlJgTFuZgzuVZJYPQfl2evkXsfsanntesy",
	"G6fjgiU29jrB7baWz0mGZ3DwZw6zOnHLE04IxVr8WgVaTdLW4P5SGJnxilQPsEB2NVHR7XPk6Go8VWf5",
	"05l5ZQ2sP5vBT8j0nCoeN0sjyewdZIfyN6OofMBrM6nKgVLfHB6Gpki1cFZwwTj63//+H7utg2MCU8bB",
	"XGkqGyIkzvIOmMy70cOt4I8klcBVjB03adnY0u9SHUzCnv30qZGdehY0unYgWme55ig8yERxmbkhtvgt",
	"qD8rzaK7Y9P6u3o8VACEsglrq1a9GtoW0AX6obbmT6hGrkS90zRuTtxdJerGdnlUWBviGlRsP8Kta57j",
	"CkIzE2/bnNDNBbVRgP/sRtAc+Z7OnEc0hK3m7WLHqpW166LrjesM3Rrh7Q7dNcUOcqH7kC3kwhsD0AV7",
	"OSpgi9CXezzh2t7XIJGocFXi2/3K+Ej20qpRBqVr5ZUl2kfO1X55+K1yqI17nabAETE1ipia2vpAsYU/",
	"UGlb2a3Q0KYdp7j6uMU9+3oDttNkvvZSccnG97oJ6xcera7MFJeDmW6EP7BjXHvKCz25utZjUFUIa6a9",
	"sqly98wKia1k9qaFSGZEz80BvKF2oqMeRlmOkdwTOAOki52xua/KSELJbC7LIbN/sknnNVRtTOyWJDY4",
	"RvfOiuyWJDQ8/jbUrWuRZGiy4yIpQ0qlU0syq5CZ1CX5CxbiHWXJj2kpLHpGI6maznhBqRtxMNx3s4vV",
	"xdmXX1/FGJ0S1jDK8rrLs2BizHQpNgf9SsxnIPfR2cd4jukMqk7fctitHno2MgOJhLnkFiPTHeGWEWjv",
	"28NvnjlV5HQhuj4PqZPXYLXJiYO5leYIBussWRs7h74TEst7fWiGxN33w9999Pct0gy3vz38JpTWdARj",
	"PnoRnkrgTim49l2lGqaYpIVOp3gdphfMiENgKijXcpN4i9u/NoEMg9mGPlvboMkl1jSe1toDazbJzhqu",
	"yD+Mxf1B39qUFmss6djy7ByCU45rC9r2HOaQeUM1rKbFpzasW0l9e1y3xlVj6PH+DR3jhak7prBsbGin",
	"AmBqO1bVewY/1fjhoDkuZGDy+VZtcnDG+o596dpw7VAmuYZcPbV65y61tsla+0Od2F/962E3yHgBKKQq",
	"Gpw+VF8oKRrmdPuDLtwA9poVVPpQMsRyoIhQ5ZxzthTA93vcZTvTPdq6VDQn43dMm6mfRvstOxORmgK2",
	"nqybYv5VOIYIxw8wq/4QQ0M6LJsNkgvd9FaKRtWL0C0cJ8ZS2RH8xgXUNRcTEPI5TKfmz4It2K2bImWg",
	"bMuGqcE3THtawTGk16F6/SvHbNKZZVzD+8QUa0ZeHLfmAYlKjwb0tq3Sca6N8yj3zB85MVz1bL87XNj+",
	"yIt1LsaTSfD6OqKF8W7y64T7gZuP2Zlm16+dmsmR22zstBM4ny4d1BlQYf/QVfhaw6C8JWkdSN++CNT2",
	"ecKoN+dwOoYtgC8ILNeQwZtb2UWH9+XEyq2RwG2x4Q2ZVsDdyroy58F6Rz1B6dNO2ykBGjRrx5+ktWbe",
	"jln4c5+286Q8BV3KUFgecOxl8Xw3Wh8/tXiq+mvaWx0C5P+57s929NvXm71/6kuB63Jirj9/TtxrClJj",
	"6KOTwFK/B1rIh1zQ/w2RqekSJ3SmcxwpLkdCMj12TkA6fW5eYbS8wTeD84IDRzQApYCvi960PHwWfeqP",
	"zpIvd8OSj9JGRtWmhswNFlP8da9+/Q6RWFMaqzFwz/q5dtGuBpsv3FYFT6Oj6ADn5GDxIrr7cPd/AQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
